// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnISt4F8GSCS5vwLn9FkMTi_q0WZCytWo',
    appId: '1:665302336531:web:e4f922bc2c61766f142be6',
    messagingSenderId: '665302336531',
    projectId: 'alqanaa-f16e4',
    authDomain: 'alqanaa-f16e4.firebaseapp.com',
    storageBucket: 'alqanaa-f16e4.firebasestorage.app',
    measurementId: 'G-04QVNK6EZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4CFwibH38yeyIajLMVepS_vpfXekcBnc',
    appId: '1:665302336531:android:d688c854a503a3a6142be6',
    messagingSenderId: '665302336531',
    projectId: 'alqanaa-f16e4',
    storageBucket: 'alqanaa-f16e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwuQqjinJFO5cakaAZc44Ew8MH2bB3kvQ',
    appId: '1:665302336531:ios:342194b1ff539a6c142be6',
    messagingSenderId: '665302336531',
    projectId: 'alqanaa-f16e4',
    storageBucket: 'alqanaa-f16e4.firebasestorage.app',
    iosBundleId: 'com.example.alqanaaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwuQqjinJFO5cakaAZc44Ew8MH2bB3kvQ',
    appId: '1:665302336531:ios:342194b1ff539a6c142be6',
    messagingSenderId: '665302336531',
    projectId: 'alqanaa-f16e4',
    storageBucket: 'alqanaa-f16e4.firebasestorage.app',
    iosBundleId: 'com.example.alqanaaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnISt4F8GSCS5vwLn9FkMTi_q0WZCytWo',
    appId: '1:665302336531:web:a938c46a5737a1a1142be6',
    messagingSenderId: '665302336531',
    projectId: 'alqanaa-f16e4',
    authDomain: 'alqanaa-f16e4.firebaseapp.com',
    storageBucket: 'alqanaa-f16e4.firebasestorage.app',
    measurementId: 'G-M5CV1RGR6L',
  );
}
