# ✅ تحديد النسخة الدنيا المطلوبة للآيفون ليتوافق مع نظام الذكاء الاصطناعي (OCR)
platform :ios, '16.0'

# Flutter-specific configurations
load File.join(File.dirname(File.expand_path(__FILE__)), 'Flutter', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    # ✅ إجبار كافة المكتبات على استخدام النسخة 16.0 لتجنب التعارضات
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
