name: Build iOS IPA

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Create IPA
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build IPA
        run: flutter build ios --release --no-codesign

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: alqanaa-ios-app
          path: build/ios/iphoneos/*.app
